import { useState } from "react";
import type { Project } from "../types";
import { Button } from "../shared/ui/Button";
import { PageHeader } from "../shared/ui/PageHeader";
import { StatusBadge } from "../shared/ui/StatusBadge";

export function HomeView({ projects, onSelect, onCreate }: { projects: Project[]; onSelect: (project: Project) => void; onCreate: (name: string) => void }) {
  const [name, setName] = useState("");
  const documents = projects.reduce((total, project) => total + project.document_count, 0);
  const sentences = projects.reduce((total, project) => total + project.sentence_count, 0);
  return <section className="home-view"><PageHeader className="home-heading" eyebrow="WORKSPACE OVERVIEW" title="Good to see you." description="Choose a project to continue writing, narrating, and exporting your audiobook." actions={<StatusBadge className="home-badge" dot tone="success">All systems connected</StatusBadge>} /><div className="overview-strip"><div><span>Projects</span><strong>{projects.length}</strong><small>Your audiobook workspaces</small></div><div><span>Documents</span><strong>{documents.toLocaleString()}</strong><small>Imported source files</small></div><div><span>Sentences</span><strong>{sentences.toLocaleString()}</strong><small>Ready to narrate</small></div></div><div className="section-heading"><div><div className="eyebrow">YOUR LIBRARY</div><h2>All projects</h2></div><span className="muted">Select a project from the cards or the sidebar.</span></div><div className="project-grid">{projects.map((project) => <button className="project-card" key={project.id} onClick={() => onSelect(project)}><span className="project-card-top"><span className="project-avatar large">{project.name.slice(0, 1).toUpperCase()}</span><span className="project-arrow">→</span></span><strong>{project.name}</strong><span>{project.document_count} documents · {project.sentence_count.toLocaleString()} sentences</span><small>Updated {new Date(project.updated_at).toLocaleDateString()}</small></button>)}<form className="project-card new-project" onSubmit={(event) => { event.preventDefault(); if (name.trim()) { onCreate(name.trim()); setName(""); } }}><span className="new-project-icon">+</span><strong>Start a new project</strong><span>Give your next audiobook a home.</span><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Project name" /><Button className="primary" type="submit">Create workspace</Button></form></div></section>;
}
