import type { ApiClient } from "../api";
import type { SettingsTab } from "../app-types";
import type { Capability } from "../types";
import { Button } from "../shared/ui/Button";
import { Card } from "../shared/ui/Card";
import { EmptyState } from "../shared/ui/EmptyState";
import { PageHeader } from "../shared/ui/PageHeader";
import { StatusBadge } from "../shared/ui/StatusBadge";

export function SettingsView({ client, capabilities, section, onSection, onBack, onDisconnect, sidebarOpen, onToggleSidebar }: { client: ApiClient; capabilities: Capability[]; section: SettingsTab; onSection: (section: SettingsTab) => void; onBack: () => void; onDisconnect: () => void; sidebarOpen: boolean; onToggleSidebar: () => void }) {
  return <div className={`settings-shell ${sidebarOpen ? "" : "settings-sidebar-closed"}`}>{sidebarOpen && <button className="settings-drawer-backdrop" type="button" tabIndex={-1} aria-label="Close settings navigation" onClick={onToggleSidebar} />}<SettingsSidebar open={sidebarOpen} section={section} onSection={onSection} onBack={onBack} onDisconnect={onDisconnect} onToggle={onToggleSidebar} /><section className="settings-content">{section === "engines" ? <EngineSettings capabilities={capabilities} /> : <AppSettings client={client} onDisconnect={onDisconnect} />}</section></div>;
}

function SettingsSidebar({ open, section, onSection, onBack, onDisconnect, onToggle }: { open: boolean; section: SettingsTab; onSection: (section: SettingsTab) => void; onBack: () => void; onDisconnect: () => void; onToggle: () => void }) {
  return <aside id="settings-sidebar" className="settings-sidebar" aria-label="Settings navigation"><div className="settings-sidebar-heading"><span className="nav-icon" aria-hidden="true">⚙</span><div><strong>Settings</strong><span>Workspace preferences</span></div><Button className="settings-sliders" variant="ghost" size="icon" type="button" aria-label={`${open ? "Close" : "Open"} settings sidebar`} aria-expanded={open} aria-controls="settings-sidebar" title={`${open ? "Close" : "Open"} settings sidebar`} onClick={onToggle}>☷</Button></div><nav id="settings-sidebar-content" className="settings-nav" aria-label="Settings sections"><Button className={`settings-nav-item ${section === "engines" ? "active" : ""}`} variant="ghost" type="button" onClick={() => onSection("engines")}><span className="nav-icon" aria-hidden="true">◈</span><span><strong>Engine settings</strong><small>Models and availability</small></span></Button><Button className={`settings-nav-item ${section === "app" ? "active" : ""}`} variant="ghost" type="button" onClick={() => onSection("app")}><span className="nav-icon" aria-hidden="true">⌘</span><span><strong>App settings</strong><small>Connection and preferences</small></span></Button></nav><div className="settings-sidebar-footer"><Button className="ghost" variant="ghost" type="button" onClick={onBack}>← Back to projects</Button><Button className="settings-disconnect" variant="destructive" type="button" onClick={onDisconnect}>Disconnect</Button></div></aside>;
}

function EngineSettings({ capabilities }: { capabilities: Capability[] }) {
  return <section><PageHeader eyebrow="ENGINE CONFIGURATION" title="TTS engines" description="Review the isolated voice engines connected to your audiobook workspace." />{!capabilities.length && <EmptyState title="No engines detected" description="Connect an engine container to configure voices and generate narration. Your projects are still available." />}<div className="engine-setting-list">{capabilities.map((capability) => { const healthy = capability.healthy !== false; return <article className="engine-setting-card" key={capability.id}><span className="engine-icon">{capability.display_name.slice(0, 1).toUpperCase()}</span><div className="engine-setting-info"><div className="engine-setting-title"><strong>{capability.display_name}</strong><StatusBadge tone={healthy ? "success" : "danger"} live="polite">{healthy ? "Available" : "Offline"}</StatusBadge></div><span>{capability.version} · {capability.requires_gpu ? "GPU engine" : "CPU capable"}</span><small>{capability.supported_languages?.join(", ") || "Languages reported by worker"}</small></div><span className="engine-setting-state">{capability.model_loaded ? "Model loaded" : "Ready to load"}</span></article>; })}</div><div className="settings-note"><span>i</span><p>Engine-specific voice and generation controls are assigned per speaker inside each project.</p></div></section>;
}

function AppSettings({ client, onDisconnect }: { client: ApiClient; onDisconnect: () => void }) {
  return <section><PageHeader eyebrow="APPLICATION SETTINGS" title="Workspace preferences" description="Manage the connection used by this desktop app." /><div className="settings-panels"><Card className="settings-panel" title="Gateway connection" description="This app is connected to your local or trusted remote server." actions={<StatusBadge className="home-badge compact" dot tone="success">Connected</StatusBadge>}><div className="setting-row"><div><span>Gateway URL</span><small>The active audiobook backend</small></div><strong>{client.baseUrl}</strong></div><div className="setting-row"><div><span>API token</span><small>Stored securely on this device</small></div><strong>••••••••••••</strong></div><Button variant="ghost" className="danger-action" onClick={onDisconnect}>Disconnect gateway</Button></Card><Card className="settings-panel" title="Appearance" description="Keep your writing workspace calm and focused."><div className="setting-row"><div><span>Theme</span><small>Application color scheme</small></div><strong>Dark studio</strong></div><div className="setting-row"><div><span>Window layout</span><small>Navigation and project panels</small></div><strong>Studio layout</strong></div></Card></div></section>;
}
