import type { ApiClient } from "../api";
import type { SettingsTab } from "../app-types";
import type { Capability } from "../types";

export function SettingsView({ client, capabilities, section, onSection, onBack, onDisconnect, sidebarOpen, onToggleSidebar }: { client: ApiClient; capabilities: Capability[]; section: SettingsTab; onSection: (section: SettingsTab) => void; onBack: () => void; onDisconnect: () => void; sidebarOpen: boolean; onToggleSidebar: () => void }) {
  return <div className={`settings-shell ${sidebarOpen ? "" : "settings-sidebar-closed"}`}><SettingsSidebar section={section} onSection={onSection} onBack={onBack} onDisconnect={onDisconnect} onToggle={onToggleSidebar} /><section className="settings-content">{section === "engines" ? <EngineSettings capabilities={capabilities} /> : <AppSettings client={client} onDisconnect={onDisconnect} />}</section></div>;
}

function SettingsSidebar({ section, onSection, onBack, onDisconnect, onToggle }: { section: SettingsTab; onSection: (section: SettingsTab) => void; onBack: () => void; onDisconnect: () => void; onToggle: () => void }) {
  return <aside id="settings-sidebar" className="settings-sidebar" aria-label="Settings navigation"><div className="settings-sidebar-heading"><span className="nav-icon" aria-hidden="true">⚙</span><div><strong>Settings</strong><span>Workspace preferences</span></div><button className="settings-sliders" type="button" aria-label="Close settings sidebar" aria-expanded="true" aria-controls="settings-sidebar" title="Close settings sidebar" onClick={onToggle}>☷</button></div><nav id="settings-sidebar-content" className="settings-nav" aria-label="Settings sections"><button className={`settings-nav-item ${section === "engines" ? "active" : ""}`} type="button" onClick={() => onSection("engines")}><span className="nav-icon" aria-hidden="true">◈</span><span><strong>Engine settings</strong><small>Models and availability</small></span></button><button className={`settings-nav-item ${section === "app" ? "active" : ""}`} type="button" onClick={() => onSection("app")}><span className="nav-icon" aria-hidden="true">⌘</span><span><strong>App settings</strong><small>Connection and preferences</small></span></button></nav><div className="settings-sidebar-footer"><button className="ghost" type="button" onClick={onBack}>← Back to projects</button><button className="settings-disconnect" type="button" onClick={onDisconnect}>Disconnect</button></div></aside>;
}

function EngineSettings({ capabilities }: { capabilities: Capability[] }) {
  return <section><div className="page-heading"><div><div className="eyebrow">ENGINE CONFIGURATION</div><h1>TTS engines</h1><p className="muted">Review the isolated voice engines connected to your audiobook workspace.</p></div></div>{!capabilities.length && <div className="settings-empty"><span className="settings-empty-icon">◌</span><div><strong>No engines detected</strong><p>Connect an engine container to configure voices and generate narration. Your projects are still available.</p></div></div>}<div className="engine-setting-list">{capabilities.map((capability) => { const healthy = capability.healthy !== false; return <article className="engine-setting-card" key={capability.id}><span className="engine-icon">{capability.display_name.slice(0, 1).toUpperCase()}</span><div className="engine-setting-info"><div className="engine-setting-title"><strong>{capability.display_name}</strong><span className={`status ${healthy ? "status-ready" : "status-failed"}`}>{healthy ? "Available" : "Offline"}</span></div><span>{capability.version} · {capability.requires_gpu ? "GPU engine" : "CPU capable"}</span><small>{capability.supported_languages?.join(", ") || "Languages reported by worker"}</small></div><span className="engine-setting-state">{capability.model_loaded ? "Model loaded" : "Ready to load"}</span></article>; })}</div><div className="settings-note"><span>i</span><p>Engine-specific voice and generation controls are assigned per speaker inside each project.</p></div></section>;
}

function AppSettings({ client, onDisconnect }: { client: ApiClient; onDisconnect: () => void }) {
  return <section><div className="page-heading"><div><div className="eyebrow">APPLICATION SETTINGS</div><h1>Workspace preferences</h1><p className="muted">Manage the connection used by this desktop app.</p></div></div><div className="settings-panels"><div className="panel settings-panel"><div className="settings-panel-heading"><div><h2>Gateway connection</h2><p className="muted">This app is connected to your local or trusted remote server.</p></div><span className="home-badge compact"><span className="status-dot" /> Connected</span></div><div className="setting-row"><div><span>Gateway URL</span><small>The active audiobook backend</small></div><strong>{client.baseUrl}</strong></div><div className="setting-row"><div><span>API token</span><small>Stored securely on this device</small></div><strong>••••••••••••</strong></div><button className="ghost danger-action" onClick={onDisconnect}>Disconnect gateway</button></div><div className="panel settings-panel"><div><h2>Appearance</h2><p className="muted">Keep your writing workspace calm and focused.</p></div><div className="setting-row"><div><span>Theme</span><small>Application color scheme</small></div><strong>Dark studio</strong></div><div className="setting-row"><div><span>Window layout</span><small>Navigation and project panels</small></div><strong>Studio layout</strong></div></div></div></section>;
}
